import Head from "next/head";
import { GetProducts } from "@/pages/api/api";
import { useEffect, useState } from "react";
import { Product } from "@/types/product";
import { GlobalStyle } from "@/styles/home";
import MainComponent from "@/components/MainComponent";
import LoadingComponent from "@/components/LoadingComponent";
import { Cart } from "@/types/cart";

export default function Home() {
  const [data, setData] = useState<Array<Product>>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [cartB, setBCart] = useState<boolean>(false);
  const [cart, setCart] = useState<Array<Cart>>([]);

  const GetData = async () => {
    try {
      const apiResult: Array<Product> = await GetProducts();
      if (apiResult.length > 0) {
        setData(apiResult);
        setLoading(false);
      }
    } catch (e) {
      setData([]);
    }
  };

  const CartButton = () => {
    setBCart(!cartB);
  };

  console.log(typeof CartButton);
  useEffect(() => {
    GetData();
  }, [loading]);

  return (
    <>
      <GlobalStyle />
      <Head>
        <title>MKS Sistemas - Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      {loading ? (
        <LoadingComponent />
      ) : (
        <MainComponent products={data} cartB={cartB} CartButton={CartButton} />
      )}
    </>
  );
}
